project:
  type: book

book:
  title: "Real Time Renderings"
  author: "Thibault Tricard"
  chapters:
    - index.qmd
    - chapitres/chapitre1.qmd

lang: fr
bibliography: references.bib

language:
  title-block-author-single: "Auteur"
  title-block-author-plural: "Auteurs"

format:
  pdf:
    documentclass: report
    classoption: [a4paper, 12pt]
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    highlight-style: github
    include-in-header: macros.tex
  html:
    theme: cosmo
    css: styles.css
